'use client';

import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/registry';
import { ThemeProvider } from 'styled-components';
import { styled } from '@/styles/styled';
import { GlobalStyle } from '@/styles/globals';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={styled}>
      <GlobalStyle></GlobalStyle>
      <html>
        <body>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ThemeProvider>
  );
}
